//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISPIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbe
    {
        public int Id { get; set; }
        public int KorisnikId { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public System.DateTime DatumKreiranja { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
    }
}
